### ISSUE TITLE
Is this correct at all?

### ISSUE THREAD

**Issue by Enerccio** [seleb/PICO-8-Token-Optimizations#3]
Either my knowledge how formal automatons and parsers/lexers work or lot of these optimizations are worse than unoptimized versions? For instance:

`var1,var2 = value1,value2` vs
```
var1 = value1
var2 = value2
```

First, optimized version, has 4(n-1)+3 tokens (var1, comma, value1, comma; var2, value2; equals) while unoptimized, since newlines do not count as tokens, has only 3n tokens? In two line example optimized version is 7 tokens (4*1 + 3) and unoptimized is 6 tokens? 

`Vector Dimensions as Properties Instead of Array Elements` a lot of mistakes, for instance it's not 9 but 11 tokens to create `point={x=x,y=y}` (point, equals, left curly, x, equals, x, comma, y, equals, y, right curly). `point[1]` is 4 tokens and `point.x` is three tokens as well...

Also string literals should be parsed as three tokens, not 1 as it is implied... "foo" should be double quote, <foo> string literal, double quote. Even if <foo> literal part is not somehow a token, that is still two tokens per string literal. Which can make repeating strings way more tokens than declaring it as constant (for Replace Constant Variables with Literals) and Calling Functions with Strings or Tables which makes only sense if your argument is string literal, otherwise you lose tokens: `foo"hello"` is 4 tokens and `foo("hello")` is 6 tokens but converting number never makes sense because `foo"6"` should be the same as `foo(6)` and you lose tokens in int->string conversion. Now, lua can be parsing string as one token internally during token stream creation so this point might be moot and subsequent points as well.

`Replace Table Elements with Separate Variables` section has bad token reduction. `player.x` vs `player_x` is two tokens down (dot is another token) so gains there could be very high especially with nested tables. So it's 2 tokens instead of 1. `Replace Multiple Table Accesses with Local Variables` same issue, it's `n-2` not `n-1` and to create it's 3+n.

`Prefer Property Access to Array Indexing` makes wrong assumption about string being one token so it saves more tokens than declared.

**Comment by seleb** [comment]
I believe you may be confusing a generic and/or formal definition of "tokens" from computer science (or maybe just from other lua parsers?) with the specific implementation of token count as an imposed restriction in PICO-8? For example, you describe strings as being three tokens, where each quotation mark is counted as a separate token, but this is not how PICO-8 works: string literals are a single token. This is easily verified in the editor:

![screenshot of PICO-8 editor with a single test string showing a token count of 1](https://user-images.githubusercontent.com/6496840/128474946-fc93387d-a914-4388-ae3f-aa12a593bd7f.png)


I double checked a couple of your other examples to find that the method of counting tokens is similarly innacurate, so I'm closing this under the assumption that it's a miscommunication, and not an error in the optimizations. Feel free to clarify and re-open if there are actual discrepancies between how PICO-8 counts tokens and what is described though (it's possible some optimizations are out of date as I have not kept up with recent PICO-8 updates).
